dyerc/Doughnut

- Doughnut/WindowController.swift
Minor thing but I found it useful, hence, sharing it.
P.S. Thanks for the work on the app.
~NOTE: please be aware that this change breaks the cmd+left and cmd+right bindings for forward/backward functionality. Hence, it is not a good idea to merge this. I just wanted to share the changes in case someone else was looking for the same.~
> toggle player by pressing space

- Doughnut/View Controllers/EpisodeViewController.swift
- Doughnut/View Controllers/PodcastViewController.swift
- Doughnut/Windows/ShowPodcastWindow.swift
This should actually fix #25.
This PR fixes crash caused by performing menu actions when no podcast or episode selected.
1. Use `@objc` to modify `validateMenuItem(_: NSMenuItem)` to ensure they're called by AppKit.
2. Instead matching menuItem with `title`, match them with `action`, strings are fragile (or maybe error prone).
3. Fixed an issue found during debugging: can't create new podcast due to `nil` passed into `ShowPodcastViewController.validate(_:)`.
> Prevent performing menu actions when no item selected to prevent crash.

- Doughnut/Library/Library.swift
- Doughnut/Preference/Preferences.storyboard
This PR fixes #22 by using `-1` as the tag for "Manually" menu option and add a specific check.
Previously "Manually" has a same tag `0` with the separator, this results the separator chosen when reopening the preference panel and, actually, podcasts got refreshed once per minute.
> Fix: choosing manual reload in preference not taking effect

- Doughnut.xcodeproj/project.pbxproj
- Doughnut/AppDelegate.swift
- Doughnut/Base.lproj/Main.storyboard
- Doughnut/Base.lproj/MainMenu.storyboard
- Doughnut/Utilities/NSMenu+Extensions.swift
- Doughnut/Utilities/NSTableView+Extensions.swift
- Doughnut/View Controllers/EpisodeViewController.swift
- Doughnut/View Controllers/PodcastViewController.swift
This PR  fixes #18, fixes #24, fixes #27, and fixes #29.
This PR contains enhancements and fixes for menus actions and shortcuts:
1. Allow bulk editing on podcasts list and episodes list. (Some actions are not supported currently, but at least for marking played or favorite.)
2. Complete actions for the "Item" main menu.
3. Support common shortcuts such as `Cmd+N`, `Cmd+shift+N`, `Cmd+Backspace`, and `Cmd+I`
4. Unifying menu items `Mark as Played` & `Mark as unplayed` into a single one with dynamic title and dash icon.
5. Slightly edited and reordered some menu items to follow best practices. 
* Bulk editing for episode list:
* Right-Click editing for single item while multiple items selected:
* Bulk actions for podcast list:
Bulk reloads for multiple podcasts is disabled currently (seems …
> Enhancements for menu actions and shortcuts.

- Doughnut.xcodeproj/project.pbxproj
- Doughnut/Base.lproj/Main.storyboard
- Doughnut/Utilities/NSView+Extensions.swift
- Doughnut/View Controllers/DetailViewController.swift
- Doughnut/View Controllers/EpisodeViewController.swift
- Doughnut/View Controllers/PodcastViewController.swift
- Doughnut/Views/PlayerView.swift
- Doughnut/Views/SortingView.swift
- Doughnut/WindowController.swift
This PR is another trial towards modern appearance (but less intrusive to current interface structure) that includes:
1. For macOS 11 & newer, use `fullSizeContentView` for main window to extend the sidebar all the way to the top and use `NSWindowToolbarStyleUnified` to enable unified toolbar.
2. Adjusts all three columns to accommodate with the safe area, especially, wrap the detail entire header into a single view (a stackView for labels), so it's easier to manage edge constraints.
3. Moves the top bar of first column to bottom. A future PR will change the the button into icon-style [Gradient Button](https://developer.apple.com/design/human-interface-guidelines/macos/buttons/gradient-buttons/).
4. Assign correct `NSSplitViewItemBehavior` for each columns, and allow the sidebar column to …
> Update sidebar and toolbar appearance for modern macOS

- Doughnut/Base.lproj/Main.storyboard
- Doughnut/View Controllers/EpisodeViewController.swift
- Doughnut/View Controllers/PodcastViewController.swift
This PR adjusts view hierarchies to enable correct translucency effects on the window header and the shadow effect beneath the header of the sidebar.
This matches most apps on macOS Big Sur and above, e.g, the Finder:
> Adjusts view hierarchies to enable correct translucency effect.

- Doughnut.xcodeproj/project.pbxproj
- Doughnut/AppDelegate.swift
- Doughnut/Base.lproj/Main.storyboard
- Doughnut/Base.lproj/MainMenu.storyboard
- Doughnut/ControlMenuProvider.swift
- Doughnut/Utilities/NSMenu+Extensions.swift
- Doughnut/View Controllers/EpisodeViewController.swift
- Doughnut/View Controllers/PodcastViewController.swift
- Doughnut/Views/BaseTableView.swift
- Doughnut/WindowController.swift
This PR:
1. Uses `ControlMenuProvider` to dynamically build 'control' menu that responds to current playback status and reflects skipping seconds set in the preference.
2. Adds a control menu to the dock (including basic controls and now playing status).
3. [Correctly](https://stackoverflow.com/questions/11155239/nsmenuitem-keyequivalent-space-bug#54006299) handles the space key for play/pause as a menu key equivalent instead of directly intercepting the event. Previous implementation prevents space characters being entered into the search bar.
Menu items being grayed out when no episode is being played:
Dock menu:
> Add control menus to the Dock and correctly handle space keyEquivalent.

- Doughnut.xcodeproj/project.pbxproj
- Doughnut/Assets.xcassets/AccentColor.colorset/Contents.json
- Doughnut/Views/EpisodeCellView.swift
- Doughnut/Views/PodcastCellView.swift
This PR adjusts drawing code to use `NSColor.controlAccentColor` to adhere to user-defined accent color, instead of drawing all interface elements in blue.
The last commit adds a Doughnut specific pink accent color. It's just an experiment for the multi-color feature and the color is derived from the app icon. Feel free to discard this commit or further tune the color.
Here's what it looks like:
> Support for user-defined accent color.

- Doughnut/AppDelegate.swift
- Doughnut/Library/Library.swift
- Doughnut/View Controllers/EpisodeViewController.swift
- Doughnut/View Controllers/PodcastViewController.swift
- Doughnut/View Controllers/ViewController.swift
- DoughnutTests/LibraryTests/LibraryTestsWithSubscription.swift
This PR refines the behaviors of tableView selection updates, especially:
1. Prevent frequent selection changes. The podcast list was frequently being force-selected when fetching new episodes and during periodic playback progress saves.
2. Preserve previously selected items after filtering podcasts or episodes.
> Refinements for selection updating behavior.

- Doughnut/Base.lproj/Main.storyboard
- Doughnut/Utilities/NSTableView+Extensions.swift
- Doughnut/View Controllers/DetailViewController.swift
- Doughnut/View Controllers/EpisodeViewController.swift
- Doughnut/View Controllers/PodcastViewController.swift
This PR fixes #58 and #63.
This PR adds necessary code to ensure list items are correctly updated when being filtered or sorted and improves the list reload performance.
Specifically, use `-[NSTableView enumerateAvailableRowViews:]` to find out visible columns and update accordingly, instead of reloading the entire list.
Currently `PodcastViewController` and `EpisodeViewController` share very similar logic regarding list reloads. Future efforts will be made to abstract these duplicate codes away.
This PR also includes a UI improvement that automatically hides the separator above the podcasts filter bar, to prevent merge conflicts.
> Improve list update performance and fix inconsistency.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/crash_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- Doughnut.xcodeproj/project.pbxproj
- Doughnut/AppDelegate.swift
- Doughnut/Base.lproj/MainMenu.storyboard
- Doughnut/CrashReport/CrashReport.storyboard
- Doughnut/CrashReport/CrashReportViewController.swift
- Doughnut/CrashReport/CrashReportWindowController.swift
- Doughnut/CrashReport/CrashReporter.swift
- Doughnut/Info.plist
- Doughnut/Preference/Preference.swift
- Doughnut/Utilities/ModalSheetSegue.swift
- Doughnut/Utilities/NSButton+Extensions.swift
- Doughnut/WindowController.swift
- Podfile
- Podfile.lock
This PR adds integration with [PLCrashReporter](https://github.com/microsoft/plcrashreporter).
A crash report window will show on the next launch after a crash to guide users to perform troubleshooting options and report it.
The "Report" button will guide the user directly to the GitHub issue template to open an issue.
Rather than upload crashes automatically to a dedicated server or integrate with an existing crash monitoring service, this approach ensures Doughnut untied with any first or third-party services and gives users their own choice of whether or not to submit crash reports.
> Add PLCrashReporter to show troubleshoot and report options on crash.

- Doughnut/Library/Library.swift
- Doughnut/Preference/Preference.swift
- Doughnut/View Controllers/EpisodeViewController.swift
- Doughnut/View Controllers/PodcastViewController.swift
- Doughnut/Windows/ShowPodcastWindow.swift
- DoughnutTests/LibraryTests/LibraryTestsWithSubscription.swift
This PR fixes #69.
The issue appears when refresh a long list of podcasts. The feed parsing call blocks the serial `taskQueue` due to network loads and all database operations piled onto the back of the queue have nearly no chance to execute, even though podcasts have been updated in memory.
This PR solves this specific problem by removing `taskQueue.async` call on database operations related to podcast, use async calls for both inserting and updating and return `Result` as callback.
> Implement async podcast saving methods that don’t block the task queue.

- Doughnut/Preference/Preferences.storyboard
This PR adds auto layout for preference panes. 
MASPreferences has a mechanism that saves frames into user defaults and restores them. Without auto layout, pane heights can be problematic at first launch after an upgrade.
> Use auto layout to determine height of preference panes.

- Doughnut/Player/Player.swift
- Doughnut/Views/PlayerView.swift
This PR utilizes `AVAsynchronousKeyValueLoading` to load episode assets asynchronously to prevent blocking the main thread. It can greatly improve the user experience, especially in low-quality network environments.
> Load audio assets asynchronously to improve the user experience.

- Doughnut/Library/Library.swift
Fixes #85.
As mentioned in #71, the `taskQueue.async` wrapper around database operations forces database writes queued to wait for long-running works in that serial taskQeuue.
PR #71 has refactored the podcast-related operations and this PR applies to those related to episodes.
> Remove taskQueue wrapper for episode DB operations to prevent queueing.

- Doughnut/Base.lproj/Main.storyboard
- Doughnut/View Controllers/PodcastViewController.swift
This PR fixes an issue on macOS 13 beta that podcast images on the sidebar are dimmed out when the main window is inactive.
> Fix: sidebar images dimmed out when window not active on macOS 13 beta.

- Doughnut/Library/Podcast.swift
Fixes #93.
This is a quick fix to allow parsing `podcasts.apple.com` URLs. Future versions will abstract the feed-detecting logic with protocols to make it easier to add support for other services.
> Support for subscribing podcasts.apple.com URLs.

- Doughnut/CrashReport/CrashReporter.swift
This PR enables symbolication for PLCrashReporter to include symbol information for system frameworks in user-submitted crash reports.
> Enable symbolication for PLCrashReporter

- Doughnut/Library/Library.swift
- Doughnut/View Controllers/EpisodeViewController.swift
- Doughnut/View Controllers/PodcastViewController.swift
- Doughnut/View Controllers/ViewController.swift
- DoughnutTests/LibraryTests/LibrarySpyDelegate.swift
- DoughnutTests/LibraryTests/LibraryTestsWithSubscription.swift
This PR improvements performance for batch (un)marking played or favourite, by using arrays as parameters for most Library delegate calls and bulk update statements.
> Performance improvements for batch (un)marking played or favourite.

- Doughnut/Player/Player.swift
Closes #87.
As discussed in #87, this PR implements an identifiable User-Agent for media playback.
Checklist:
After merging this PR, user agent patterns should be submitted to [opawg/user-agents](https://github.com/opawg/user-agents) and [opawg/podcast-rss-useragents](https://github.com/opawg/podcast-rss-useragents). Simple regex patterns like `Doughnut` should be enough to distinguish Doughnut from other clients.
> Implement custom User-Agent for media playback

- Doughnut/Player/Player.swift
- Doughnut/Preference/Preference.swift
- Doughnut/Preference/Preferences.storyboard
This PR fixes #106.
@GetToSet would you mind reviewing please. It seemed necessary to have an additional observer event for when the player finishes playback. Do you think we should reset the player visual state at this point? Currently it just stays the same but with 0:00 remaining on the clock (as it always has done). Nothing necessarily short-term, but it was something that occurred to me.
> Add a playback threshold percentage at which point to mark an episode as played
